name: Testing workflow

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install

      - name: Running tsc
        run: yarn tsc

      - name: Running tests with jest
        run: yarn test

      - name: Clean Git Status
        uses: numtide/clean-git-action@v1
